### ISSUE TITLE
Intermittent i/o timeout errors from db requests

### ISSUE THREAD

**Issue by snormore** [xmtp/xmtp-node-go#246]
We're seeing intermittent `i/o timeout` errors from interactions with the DB ([logs](https://app.datadoghq.com/logs?query=%28%22api%20request%22%20%40error%3A%2A%3F%2A%29%20OR%20%22storing%20message%22%20AND%20NOT%20%40error_code%3APermissionDenied%20AND%20NOT%20%40error_code%3AUnauthenticated&cols=env%2C%40method%2C%40error_code%2C%40error&index=%2A&messageDisplay=inline&saved-view-id=1307395&stream_sort=time%2Cdesc&viz=stream&from_ts=1675803253708&to_ts=1676408053708&live=true)), with about 2k of them on `Query` in the past week, and ~700 of them on `storing message` in the same time, with 600 of them during a [writer restart initiated by AWS last week](https://xmtp-labs.slack.com/archives/C03RBRMEPSR/p1676072755724999).

We should figure out why these are happening and resolve. In the case of the writer restart scenario, we might want to consider adding some inline retries to avoid the full api request failure.

**Comment by desssai** [comment]
I think it may be related to the innner implementation of pgdriver.
 It does not state this in the documentation, but the driver actually sets the read and write timeout under-the-hood. 
 
 
![image](https://github.com/user-attachments/assets/199be2ad-4dd6-42ca-961c-607b021a623e)

It does not say anything regarding those defaults in the documentation.
In my case, setting the timeout explicitly helped.
