### ISSUE TITLE
Feature request: Stop unwrapping MLS messages when publishing to the network

### ISSUE THREAD

**Issue by neekolas** [xmtp/xmtp-node-go#324]
### Is your feature request related to a problem?

When I initially set up the MLS endpoints, I decided to unwrap the protobufs and just publish the MLS payloads to the network (`Welcome`s and `MlsMessage` tls serialized bodies). That makes upgrading to newer MLS serialization formats difficult in the future. 

### Describe the solution to the problem

We should not unwrap the MLS messages and instead re-serialize the message content protos before writing to the network. This will require some changes in `libxmtp` to calculate the hashes on the proto message instead of the inner MLS message.

### Describe the uses cases for the feature

Upgrading `openmls` in the future

**Comment by snormore** [comment]
@neekolas can we call this one done?
